### PR TITLE
Call note api changes

### PR DESCRIPTION
**Pull request by justinvdm**
Changes to match what the app is expecting from the api.

@nathanbegbie ready for review

### CODE REVIEW

**Comment by nathanbegbie** [comment]
I'll fix those flake8 errors quickly

**Comment by justinvdm** [comment]
🍰  for flake8 fixing :)

**Comment by nathanbegbie** [comment]
@justinvdm I think there needs to be additional tests for this in `test_v2_views.py`

**Comment by justinvdm** [comment]
@nathanbegbie ready for review

**Comment by nathanbegbie** [comment]
😍 :+1:

**Pull request merged**
