### PR TITLE
updating copy sent to mentee when call scheduled

### PR DESCRIPTION
**Pull request by codiebeulaine**
@justinvdm ready for review

### CODE REVIEW

**Comment by justinvdm** [comment]
:+1:

**Comment by codiebeulaine** [comment]
@justinvdm ready for review again

**Comment by justinvdm** [comment]
First prize would be to change the tests to use hardcoded date values for the input dates and output messages, since that would make for much stronger tests, but if that is more work than its worth, happy with this landing.

**Comment by justinvdm** [comment]
Would also be awesome if we could wrap up this timezone stuff into a util, but same case as above, happy with this landing if that is more work than it is worth.

**Comment by justinvdm** [comment]
👍 wtih :cake::cake: util and tests look awesome :)

**Pull request merged**
