### PR TITLE
Proposed update to feedback API

### PR DESCRIPTION
**Pull request by hodgestar**
We'd like to add a new field, `complete`, that indicates whether the feedback survey results are partial or fully complete.

### CODE REVIEW

**Comment by hodgestar** [comment]
Complete example of the new JSON:
```javascript
{
          "count": 1,
          "next": null,
          "previous": null,
          "results": [
              {
                  "id": 1,
                  "sender_id": 2,
                  "call_id": 1,
                  "complete": true,
                  "content": "\"[{u'question 6': u'Purple', u'question 4': u'No', u'question 5': u'4', u'question 2': u'Yes', u'question 3': u'Yes', u'question 1': 1}]\""
              }
          ]
        }
```

**Comment by hodgestar** [comment]
@bruskiza Would one of you mind reviewing this and :+1:ing once you're happy with the docs?

In the mean time I will work on adding it in #87.

**Comment by hodgestar** [comment]
I've discovered that this documentation is out of date. I will update it shortly.

**Comment by codiebeulaine** [comment]
👍

**Pull request merged**
