### PR TITLE
Create and reconcile CDRs

### PR DESCRIPTION
**Pull request by justinvdm**
We need to create cdrs (call data records) given by OnionDev and reconcile cdrs given later so that we are only creating cdrs that do not yet exist.

### CODE REVIEW

**Comment by justinvdm** [comment]
@codiebeulaine ready for review

**Comment by justinvdm** [comment]
Depends on #201.

**Comment by justinvdm** [comment]
Ready for review now.

**Comment by codiebeulaine** [comment]
👍

**Pull request merged**
